# Generated by Django 3.2.18 on 2023-03-31 15:32

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('state_pages', '0002_stateadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateeditor',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name='statepage',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
