# Generated by Django 3.2.18 on 2023-03-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_show_for_donation'),
        ('donations', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='donate_to_chapter',
        ),
        migrations.AddField(
            model_name='transaction',
            name='donate_to_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity'),
        ),
    ]
