name: moms-for-liberty

services:

  #############################################################################
  # Base
  #############################################################################

  nginx-base:
    image: nginx:1.21-alpine
    restart: unless-stopped
    volumes:
      - ./momsforliberty:/var/www/momsforliberty:ro

  tendenci-base:
    build:
      context: .
      # Work-around for security policies on the server
      network: host
      # Build the container user as the same UID as the host user
      args:
        - "USER_UID=${HOST_UID:-1000}"
        - "USER_GID=${HOST_GID:-1000}"
    # Run the container as the same UID as the host user
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file: ${ENV_FILE:-.env}

  #############################################################################
  # Development
  #############################################################################

  nginx-development:
    extends:
      service: nginx-base
    depends_on:
      - tendenci-development
    volumes:
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  tendenci-development:
    extends:
      service: tendenci-base
    build:
      target: development
    depends_on:
      db:
        condition: service_healthy
      maildev:
        condition: service_healthy
    ports:
      - "${TENDENCI_PORT:-8000}:8000"
    volumes:
      - ./m4l-tendenci:/app/m4l-tendenci
      - ./momsforliberty:/app/momsforliberty
    environment:
      - "DJANGO_DEBUG=True"
      # db service
      - "DATABASE_HOST=db"
      # maildev service
      - "MAIL_HOST=maildev"
      - "MAIL_PORT=1025"
      - "MAIL_USER="
      - "MAIL_PASSWORD="

  #############################################################################
  # Production
  #############################################################################

  nginx-production:
    extends:
      service: nginx-base
    depends_on:
      - tendenci-production
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl.certificate.pem:/etc/nginx/ssl.certificate.pem:ro
      - ./nginx/ssl.private_key.pem:/etc/nginx/ssl.private_key.pem:ro
    ports:
      - "80:80"
      - "443:443"

  tendenci-production:
    extends:
      service: tendenci-base
    build:
      target: production
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
      maildev:
        condition: service_healthy
    volumes:
      - ./momsforliberty/media:/app/momsforliberty/media
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "MEMCACHED_HOST=memcached"
      - "MEMCACHED_PORT=11211"

  #############################################################################
  # Supporting Services
  #############################################################################

  db:
    image: postgis/postgis:14-3.3-alpine
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      # Don't touch this directory directly!
      - ./postgresql/data:/var/lib/postgresql/data
      # The seed file is mounted here so that `make db-seed` can access it
      - ./postgresql/seed.dump:/seed.dump:ro
    # This env_file is generated by the Makefile based on the 1Password environment!
    env_file: postgresql/.env
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - --host=localhost 
        - --port=5432
        - --username=$$POSTGRES_USER
        - --dbname=$$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached:1.5.22-alpine
    restart: unless-stopped
    ports:
      - '${MEMCACHED_PORT:-11211}:11211'
    command: -m 64

  maildev:
    build: maildev
    restart: unless-stopped
    ports:
      - "${MAILDEV_WEB_PORT:-1080}:1080"
      - "${MAILDEV_SMTP_PORT:-1025}:1025"

  playwright:
    build: playwright
    network_mode: host
    env_file: ${ENV_FILE:-.env}
    volumes:
      - ./playwright:/playwright