# Generated by Django 3.2.17 on 2023-02-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_auto_20220808_1704'),
        ('contacts', '0004_auto_20200902_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, default=0, verbose_name='Sort Order')),
                ('status', models.BooleanField(default=True)),
                ('status_detail', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=40)),
                ('group_name', models.CharField(max_length=254)),
                ('is_newsletter', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, default=0, verbose_name='Sort Order')),
                ('status', models.BooleanField(default=True)),
                ('status_detail', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('is_newsletter_subscribed', models.BooleanField(default=True)),
                ('newsletter_key', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Contact Group Membership',
                'verbose_name_plural': ' Contact Group Memberships',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='company',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='company',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='company',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_anonymous_view',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_member_edit',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_member_view',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_user_edit',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_user_view',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='creator_username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='owner_username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status_detail',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AddField(
            model_name='contactgroupmembership',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactgroupmembership',
            name='contact_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_group_member', to='contacts.contactgroup'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(related_name='contact_groups', through='contacts.ContactGroupMembership', to='contacts.Contact'),
        ),
        migrations.AlterUniqueTogether(
            name='contactgroupmembership',
            unique_together={('contact', 'contact_group')},
        ),
    ]
