---

- name: Modify ssh config
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.ssh/config"
    create: true
    block: "{{ lookup('template', 'ssh_config.j2') }}"
    owner: "{{ user }}"
    mode: "0644"

- name: Checkout the project
  ansible.builtin.git:
    key_file: "{{ key_file }}"
    accept_hostkey: true
    repo: "{{ repo }}"
    dest: "{{ checkout_root }}"
    version: "{{ checkout_branch }}"
    update: true
