# Generated by Django 3.2.18 on 2023-03-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20230323_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteer_enabled',
            field=models.BooleanField(default=False, help_text='Enable Volunteer'),
        ),
    ]
